In [8]:
import gymnasium as gym
import skyscraper
from sklearn.neural_network import MLPRegressor
import numpy as np
from sklearn.preprocessing import StandardScaler

# ex5


In [9]:
trajectories = np.loadtxt("powered_flight.txt", dtype=int)  # Reads as integers
print(trajectories)


[[18 17  1  0 17 13]
 [ 4 61  1  0  4 57]
 [12 20  2  0 11 23]
 ...
 [11 19  1  0 12 16]
 [ 9  8  1  0 10  5]
 [ 5 27  2  0  4 30]]


In [10]:
#Transistion function

def transition_function(trajectories):
    transition_dict = {}

    for step in trajectories:
        state = (step[0], step[1])  # Current state (assuming 2D state)
        action = step[2]  # Action taken
        new_state = (step[4], step[5])  # Next state (assuming 2D state)

        # Store multiple transitions per (state, action) pair
        if (state, action) not in transition_dict:
            transition_dict[(state, action)] = []
        
        transition_dict[(state, action)].append(new_state)

    return transition_dict

print(transition_function(trajectories))

{((np.int64(18), np.int64(17)), np.int64(1)): [(np.int64(17), np.int64(13))], ((np.int64(4), np.int64(61)), np.int64(1)): [(np.int64(4), np.int64(57))], ((np.int64(12), np.int64(20)), np.int64(2)): [(np.int64(11), np.int64(23))], ((np.int64(17), np.int64(10)), np.int64(2)): [(np.int64(19), np.int64(12))], ((np.int64(8), np.int64(15)), np.int64(1)): [(np.int64(9), np.int64(12))], ((np.int64(3), np.int64(38)), np.int64(1)): [(np.int64(3), np.int64(35))], ((np.int64(18), np.int64(17)), np.int64(2)): [(np.int64(17), np.int64(21))], ((np.int64(5), np.int64(56)), np.int64(1)): [(np.int64(5), np.int64(52))], ((np.int64(4), np.int64(40)), np.int64(2)): [(np.int64(2), np.int64(43))], ((np.int64(3), np.int64(59)), np.int64(2)): [(np.int64(3), np.int64(64))], ((np.int64(3), np.int64(57)), np.int64(2)): [(np.int64(4), np.int64(61))], ((np.int64(2), np.int64(54)), np.int64(1)): [(np.int64(3), np.int64(52))], ((np.int64(10), np.int64(14)), np.int64(2)): [(np.int64(11), np.int64(17))], ((np.int64(19)

In [11]:
def reward_function(trajecotries):
    reward_dict = {}

    for step in trajectories:
        state = (step[0], step[1])  # Current state (assuming 2D state)
        action = step[2]  # Action taken
        reward = step[3]

        # Store multiple transitions per (state, action) pair
        if (state, action) not in reward_dict:
            reward_dict[(state, action)] = []
        
        reward_dict[(state, action)].append(reward)

    return reward_dict

print(reward_function(trajectories))

{((np.int64(18), np.int64(17)), np.int64(1)): [np.int64(0)], ((np.int64(4), np.int64(61)), np.int64(1)): [np.int64(0)], ((np.int64(12), np.int64(20)), np.int64(2)): [np.int64(0)], ((np.int64(17), np.int64(10)), np.int64(2)): [np.int64(0)], ((np.int64(8), np.int64(15)), np.int64(1)): [np.int64(0)], ((np.int64(3), np.int64(38)), np.int64(1)): [np.int64(0)], ((np.int64(18), np.int64(17)), np.int64(2)): [np.int64(0)], ((np.int64(5), np.int64(56)), np.int64(1)): [np.int64(0)], ((np.int64(4), np.int64(40)), np.int64(2)): [np.int64(0)], ((np.int64(3), np.int64(59)), np.int64(2)): [np.int64(0)], ((np.int64(3), np.int64(57)), np.int64(2)): [np.int64(0)], ((np.int64(2), np.int64(54)), np.int64(1)): [np.int64(0)], ((np.int64(10), np.int64(14)), np.int64(2)): [np.int64(0)], ((np.int64(19), np.int64(58)), np.int64(2)): [np.int64(0)], ((np.int64(2), np.int64(56)), np.int64(1)): [np.int64(0)], ((np.int64(8), np.int64(11)), np.int64(2)): [np.int64(0)], ((np.int64(4), np.int64(54)), np.int64(2)): [np.i

In [12]:
def create_model(trajectories):
    X = trajectories[:, :3]  # (state1, state2, action)
    y = trajectories[:, 3:]  # (new_state1, new_state2)

    print(y)
    
    # Ensure input is numerical
    scaler_X = StandardScaler()
    scaler_y = StandardScaler()

    X_scaled = scaler_X.fit_transform(X)
    y_scaled = scaler_y.fit_transform(y)

    # Train model
    nn = MLPRegressor(hidden_layer_sizes=(64, 64), activation='relu', solver='adam', max_iter=5000)
    nn.fit(X_scaled, y_scaled)

    return nn, scaler_X, scaler_y

# Create model
model, scaler_X, scaler_y = create_model(trajectories)

# Prepare input for prediction
test_input = np.array([[4, 61, 1]])  # Flattened input (state1, state2, action)
test_input_scaled = scaler_X.transform(test_input)  # Scale input

# Make prediction
prediction_scaled = model.predict(test_input_scaled)  # Predict in scaled space
prediction = scaler_y.inverse_transform(prediction_scaled)  # Convert back

# Round to 2 decimal places
prediction = np.round(prediction, decimals=2)

print(prediction)  # Predicted new state with fewer decimals



[[ 0 17 13]
 [ 0  4 57]
 [ 0 11 23]
 ...
 [ 0 12 16]
 [ 0 10  5]
 [ 0  4 30]]
[[-0.    4.38 57.05]]


In [13]:
env = gym.make('skyscraper/GridWorld-v0')

In [14]:
def q_learning(s, a, r, new_s, ):
   ...

In [15]:
def Dyna(env, model, policy, beta, gamma, n, w):
    model = model
    w = w
    for k in range(1, 100):
        #take action
        #collect reward and new state
        #w(k+1) = QLearning(s, a, r, s´, ...)
        #model(k+1)=update_model(s, a, r, s´,...)

        for m in range(1, 100):
            #select random a and s
            r, new_s = model.predict(state, a)
            #w(k+1) = QLearning(s, a, r, s´, ...)


    optimal_policy = ...
    return optimal_policy

#Chat kode

In [16]:
import random
def choose_action(state, action_size, Q, epsilon):
        """Epsilon-greedy action selection."""
        if np.random.rand() < epsilon:
            return np.random.choice(action_size)  # Explore
        return np.argmax(Q[state, :])  # Exploit

def learn(state, action, reward, next_state, Q, alpha, gamma):
    """Q-learning update rule."""
    best_next_action = np.argmax(Q[next_state, :])
    Q[state, action] += alpha * (reward + gamma * Q[next_state, best_next_action] - Q[state, action])

def update_model(state, action, reward, next_state):
    """Store the transition in the model."""
    model[(state, action)] = (reward, next_state)

def planning(model, planning_steps):
    """Simulate experience using the model."""
    for _ in range(planning_steps):
        if not model:
            break  # No stored transitions yet

        # Sample a random (state, action) pair from the model
        (s, a), (r, s_next) = random.choice(list(model.items()))

        # Update Q-table using the simulated experience
        learn(s, a, r, s_next)

In [23]:
def dyna_q(env, model, alpha=0.1, gamma=0.95, epsilon=0.1, planning_steps=10, episodes=500):
    """
    Implements the Dyna-Q reinforcement learning algorithm.
    
    Parameters:
        env: The environment (assumed to follow OpenAI Gym-like API).
        alpha: Learning rate.
        gamma: Discount factor.
        epsilon: Exploration probability.
        planning_steps: Number of simulated updates per real step.
        episodes: Number of episodes to train.

    Returns:
        Q-table (state-action values) and optimal policy.
    """

    state_size = len(env.observation_space)
    action_size = env.action_space.n

    # Initialize Q-table
    Q = np.zeros((state_size, action_size))

    # Model: Dictionary storing transitions {(state, action): (reward, next_state)}
    model = model

    # Training loop
    for episode in range(episodes):
        state = env.reset()
        done = False

        while not done:
            action = choose_action(state, action_size, Q, epsilon)
            next_state, reward, done, _ = env.step(action)

            # Real experience update
            learn(state, action, reward, next_state, Q, alpha, gamma)

            # Update model
            update_model(state, action, reward, next_state)

            # Simulated experience (planning)
            planning(model, planning_steps)

            state = next_state

    # Derive optimal policy from Q-table
    optimal_policy = np.argmax(Q, axis=1)
    return Q, optimal_policy

dyna_q(env=env, model=create_model(trajectories))

[[ 0 17 13]
 [ 0  4 57]
 [ 0 11 23]
 ...
 [ 0 12 16]
 [ 0 10  5]
 [ 0  4 30]]


/Users/christofferslettebo/anaconda3/envs/inf266/lib/python3.11/site-packages/gymnasium/utils/passive_env_checker.py:134: UserWarning: WARN: The obs returned by the `reset()` method was expecting numpy array dtype to be int32, actual type: int64
  logger.warn(
/Users/christofferslettebo/anaconda3/envs/inf266/lib/python3.11/site-packages/gymnasium/utils/passive_env_checker.py:158: UserWarning: WARN: The obs returned by the `reset()` method is not within the observation space.
  logger.warn(f"{pre} is not within the observation space.")


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices